### ISSUE TITLE
unable to connect to idrive e2

### ISSUE THREAD

**Issue by MyUncleSam** [photosync/android-photosync-s3#18]
Hallo,

I started a trial period today and tried to connect my phone to a brand new iDrive e2 bucket. But all I got was an error.

I tried to enter the credentials multiple times. I also used AutoHotkey to copy paste them over a remote connection to avoid any typo errors. But nothing worked.

Can it be, that the S3 support for iDriver e2 is broken?

Details about my iDrive e2 configuration:
- Location is Frankfurt in germany (I think the code is 'fra' but not sure)
- bucket is completely new
- access keys are also new and only have permission for this single bucket
- 'Default encryption', 'Objekt lock' and 'Versioning' are disabled - private bucket

![image](https://user-images.githubusercontent.com/12820919/195603523-b2e1d0f2-a60b-4777-b442-2d6b71af26b2.png)

**Comment by tomekit** [comment]
Thanks for reporting this.

I've tested iDrive for Paris and Ireland (Frankfurt isn't available to me due to lack of capacity currently) and it worked just fine.

![Screenshot from 2022-10-13 20-21-23](https://user-images.githubusercontent.com/7759113/195676248-c6ac78a9-9b2d-4693-a23a-ccfb78cd684c.png)

Since you've received the: AmazonClientException, can you please go to application logs and see what's there? 
If it's not clear to you about it's meaning, please send it over. If you don't feel comfortable publishing it here, please contact me directly at: traganowicz@syncaware.com.
Please find here how to access logs: https://github.com/photosync/android-photosync-s3/issues/16#issuecomment-1256935294

I can only speculate, but can you please double check if credentials (access key and secret) and bucket belong to the same region?

**Comment by MyUncleSam** [comment]
Hi @tomekit ,

thank you for your fast response. I entered the credentials and checked twice. The logs showed credentials and certificate errors.

I removed the repository and recreated it with new credentials. And it worked out of the box. So this can be closed now. Thank you very much for your help.
