### ISSUE TITLE
[FEATURE] option to share cloud link for individual photos and for whole album

### ISSUE THREAD

**Issue by navehay** [photosync/android-photosync-s3#8]
So that the person can see also preview with thumbnails

**Comment by tomekit** [comment]
Thanks, this feature is being worked on. It takes longer than normal, as we're also building E2E encryption, which makes file sharing way more complex.

**Comment by tomekit** [comment]
This is to let you know that file sharing for photos&videos was released in version 1.4.4 as beta feature.
In order to share the whole album you can select all of the media using double selection.

It has some limitations (e.g. max 24 hours validity period, no easy way to revoke the share before the expiration period, pretty long share link) dictated by the "no-middleman app design" around S3 protocol, however there are many ways in which this can be improved.

Please let me know how do you like sharing feature.

**Comment by navehay** [comment]
Thanks, I'll check it out.

בתאריך יום ב׳, 12 בספט׳ 2022, 23:59, מאת Tomasz Raganowicz ‏<
***@***.***>:
